/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jfilesyncer;

public class App {

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
