/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jfilesyncer;

import jfilesyncer.services.GDriveService;
import jfilesyncer.services.GoogleOauth2Service;

import java.io.IOException;
import java.util.logging.Logger;

public class App {

  private static final Logger logger = Logger.getLogger(App.class.getName());

  public static void main(String[] args) {
    try {
      var service = new GoogleOauth2Service();
      service.loadCredentials();
      logger.info("Result is " + String.valueOf(service.credentialsAvailable()));

    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

  private static void init() {}
}
